name: Deploy to cPanel (FTP Only)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, zip
        tools: composer:v2

    - name: Install Node Dependencies
      run: npm ci

    - name: Build Assets
      run: npm run build
        
    - name: Install PHP Dependencies
      run: composer install --no-dev --optimize-autoloader --no-scripts
      
    - name: Create production .env
      run: |
        cp .env.production.example .env
        php artisan key:generate --ansi
        
    - name: Cache Laravel configurations
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env.example
          .env.production.example
          tests/**
          .phpunit.result.cache
          README.md
          package*.json
          vite.config.js
          phpunit.xml